### ISSUE TITLE
Comment Remover opens Configure Code Cleanup when CTRL K,Q is pressed

### ISSUE THREAD

**Issue by njsokalski** [madskristensen/CommentRemover#2]
### Installed product versions
- Visual Studio: Visual Studio 2019 Community 16.0.2
- This extension: 1.3.25

### Description
This was one of my favorite Extensions in Visual Studio 2017, and I recently started working on updating my apps with Visual Studio 2019. However, in Visual Studio 2019, CTRL K,Q (which is what I used in Visual Studio 2017 for this Extension), is opening the Configure Code Cleanup window. This is a feature that I am new to, but since all I want right now is to remove the comments (I don't want to do anything complex), I don't want to worry about the fancy configuration of Code Cleanup. What do you suggest?

### Steps to recreate
1. Install Comment Remover Extension in Visual Studio 2019
2. Open file containing comments
3. Press CTRL K,Q

### Current behavior
CTRL K,Q is opening the Configure Code Cleanup window

### Expected behavior
CTRL K,Q should execute Comment Remover to remove comments

**Comment by madskristensen** [comment]
You can manually force the keybinding in Tools -> Options, but in VS 2019 v16.1 the shortcut for Configure Code Cleanup will be removed and this extension will go back to functioning like advertised.
